UserProfile/urls.py
from django.conf.urls import url
from django.urls import path

from UserProfile import views

app_name = 'UserProfile'
urlpatterns = [
    url('getusers/', views.get_users, name='getusers'),
    url('add_friend/', views.addfriend, name='addfriend'),
    path('friend/<int:id>/', views.get_friend_detail, name='get_friend_detail'),
    path('settleup/', views.settle_up, name='settle_up'),
]

dng/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.urls import path
from dng import views

app_name = 'dng'
urlpatterns = [
    url('create', views.create, name='create'),
    url('seen_notification', views.seen_notification, name='seen_notification'),

    url('', views.index, name='index')
]

dong/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.urls import path
from dng.views import *
from dong import views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', index, name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/profile', views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('users/', include('UserProfile.urls')),
    path('group/', include('group.urls')),
    path('dng/', include('dng.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/index.html
{% extends "account/base.html" %}

{% block title %}
    Dong
{% endblock %}

{% if user.is_authenticated %}
    {% block lmenu %}
        {#        {% with x='mehran' %}#}
        {#            {{ block.super }}#}
        {#        {% endwith %}#}
    {% endblock %}
{% endif %}

{% block content %}

    {% if user.is_authenticated %}
        <div class="row">
            <div  class="col s12 light_primary_color" style="height: 90px; border-bottom: 1px solid lightgrey;">
                <h4 class="left-align col s2">Dashboard</h4>
                <a class="modal-trigger" href="#cdong-modal">
                    <button data-step="2" data-intro="Add Dong Here"  style="margin-top: 25px;"
                            class="col s2 btn-flat text_icons push-s7 btn waves-effect waves-light accent_color">Add
                        Dong
                    </button>
                </a>
            </div>

            <div data-step="5" data-intro="Your Total Balance" class="col s4 bottom-border light_primary_color" style="height: 70px;">
                <div class="center">
                    <p style="margin-bottom: 0px;" class="secondary_text">total balance</p>
                    <a class="{% if user.get_total_balance < 0 %} owe-color {% endif %}">{{ user.get_total_balance }}</a>
                </div>

            </div>

            <div class="col s4 bottom-border light_primary_color" style="height: 70px;">
                <div class="center">
                    <p style="margin-bottom: 0px;" class="secondary_text">you owe</p>
                    <a class="owe-color">{{ user.get_owes_sum }}</a>
                </div>

            </div>

            <div class="col s4 bottom-border light_primary_color" style="height: 70px;">
                <div class="center">
                    <p style="margin-bottom: 0px;" class="secondary_text">you are owed</p>
                    <a>{{ user.get_credits_sum }}</a>
                </div>

            </div>

            <div data-step="3" data-intro="People You Owe" class="col s6 no-padding">
                <div class="collection no-padding borderless-collection">
                    <a class="collection-header borderless-collection"><h6 style="margin-left: 10px"
                                                                           class="align-left secondary_text">You
                        Owe</h6></a>
                    {% for user, amount in user.get_owes.items %}
                        {# may need tooltip#}
                        <a href="{% url 'UserProfile:get_friend_detail' user.id %}" class="collection-item avatar borderless-collection">
                            <img src="{{ user.get_picture }}" alt="" class="circle">
                            <span class="title primary_text">
                                {{ user.username }}
                            </span>
                            <p class="owe-color">you owe <b>{{ amount }}</b></p>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div data-step="4" data-intro="People Who Owe You" class="col s6 no-padding">
                <div class="collection no-padding borderless-collection">
                    <a class="collection-header borderless-collection"><h6 style="margin-right: 10px"
                                                                           class="right-align secondary_text">You
                        Are Owed</h6></a>
                    {% for user, amount in user.get_credits.items %}
                        {# may need tooltip#}
                        <a href="{% url 'UserProfile:get_friend_detail' user.id %}" class="collection-item avatar borderless-collection">
                            <img src="{{ user.get_picture }}" alt="" class="circle">
                            <span class="title primary_text">
                                {{ user.username }}
                            </span>
                            <p>owes you <b>{{ amount }}</b></p>

                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        {% load static %}




        <div class="row section">
            <div class="col s12 section">
                <img style="padding-top: 10px" class="left" width="150" src="{% static 'images/dong.png' %}">
                <h2 class="left secondary_text"><b>Split expenses with friends.</b></h2>
            </div>
            <div class="col s12">
                <h6 class="center"><b>Share</b> bills and expenses> with your <b>friends</b>. create <b>groups</b>
                    for easy management. Make sure everyone gets paid back.</h6>
            </div>
            <div class="col s12 center section" style="padding-top: 20px;">
                <img class="z-depth-2" width="60%" src="{% static 'images/secondImage.png' %}">
            </div>

            <div class="center col s12" style="padding-top: 30px;">
                <a href="/accounts/signup">
                    <button style="width: 30%; height: 80px;"
                            class="section btn z-depth-3 waves-effect accent_color"><h6><b>Lets Get Started
                        Now</b><br></h6>for free

                    </button>
                </a>
            </div>


        </div>
        <div class="divider"></div>

        <div class="row section" style="margin-top: 80px;">

            <div class="col s4 center">
                <i class="material-icons secondary-icons-text large">people</i>
                <h4><b>Interact With Your Friends</b></h4>
                <div class="col s10 push-s1">
                    <p>Comment on bills, make announcements in group. Talk to your
                        friends about your expenses.</p>
                </div>
            </div>
            <div class="col s4 center">
                <i class="material-icons large secondary-icons-text">call_split</i>
                <h4><b>Split Your Bills As You Wish</b></h4>
                <div class="col s10 push-s1">
                    <p>You can split your bills and expenses in different ways, you can manage bills in groups and with
                        your friends.</p>
                </div>
            </div>
            <div class="col s4 center">
                <i class="material-icons large secondary-icons-text">payment</i>
                <h4><b>Pay And Get Paid Easily</b></h4>
                <div class="col s10 push-s1">
                    <p>You can pay your debts and settle up easily with <b>DONG</b>. get announcement of payments you do
                        and get.</p>
                </div>
            </div>

        </div>

        <div class="divider"></div>

        <div class="col s12 section" style="margin-top: 120px;">
            <i class="material-icons medium left section">crop_free</i>
            <h4 class="col s7center">And of course it is <b>totally</b> free</h4>

            <a href="/accounts/signup">
            <button style="width: 30%; height: 80px;"
                    class="right section btn z-depth-3 waves-effect accent_color"><h6><b>Lets Get Started
                Now</b><br></h6>

            </button>
                </a>

        </div>

        <div class="divider"></div>

        <div class="row section" style="margin-top: 400px;">
            <div class="center col s12">
                <h3>OUR AMAZING TEAM</h3>
            </div>
            <div class="row">
                <div class="col s6 center">
                    <img src="{% static "images/mehran.jpg" %}" style="border-radius: 50%; height: 25%; border: 5px solid #4CAF50">
                    <h5><b>Mehran Aghabozorgi</b></h5>
                    <div class="col s10 push-s1">
                        <p style="font-size: 130%; margin-top: 0%" class="secondary_text">Developer</p>
                    </div>
                </div>
                <div class="col s6 center">
                    <img src="{% static "images/mamad.jpg" %}" style="border-radius: 50%; height: 25%; border: 5px solid #4CAF50">
                    <h5><b>Mohammad Dehghan</b></h5>
                    <div class="col s10 push-s1">
                        <p style="font-size: 130%; margin-top: 0%" class="secondary_text">Developer</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col s6 center">
                    <img src="{% static "images/hadis.jpg" %}" style="border-radius: 50%; height: 25%; border: 5px solid #4CAF50">
                    <h5><b>Hadis Masaeli</b></h5>
                    <div class="col s10 push-s1">
                        <p style="font-size: 130%; margin-top: 0%" class="secondary_text">Designer</p>
                    </div>
                </div>
                <div class="col s6 center">
                    <img src="{% static "images/amirhossein.jpg" %}" style="border-radius: 50%; height: 25%; border: 5px solid #4CAF50">
                    <h5><b>AmirHossein Bahrami</b></h5>
                    <div class="col s10 push-s1">
                        <p style="font-size: 130%; margin-top: 0%" class="secondary_text">Developer</p>
                    </div>
                </div>

            </div>

        </div>

    {% endif %}
{% endblock %}