UserProfile/urls.py
from django.conf.urls import url
from django.urls import path

from UserProfile import views

app_name = 'UserProfile'
urlpatterns = [
    url('getusers/', views.get_users, name='getusers'),
    url('add_friend/', views.addfriend, name='addfriend'),
    path('friend/<int:id>/', views.get_friend_detail, name='get_friend_detail'),
    path('settleup/', views.settle_up, name='settle_up'),
]

dng/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.urls import path
from dng import views

app_name = 'dng'
urlpatterns = [
    url('create', views.create, name='create'),
    url('seen_notification', views.seen_notification, name='seen_notification'),

    url('', views.index, name='index')
]

dong/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include
from django.urls import path
from dng.views import *
from dong import views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', index, name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/profile', views.profile, name='profile'),
    path('accounts/', include('allauth.urls')),
    path('users/', include('UserProfile.urls')),
    path('group/', include('group.urls')),
    path('dng/', include('dng.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/user/friendDetail.html
{% extends 'base.html' %}
{% load static %}
{% load dong_tags %}

{% block title %}
    {{ res.friend.username }}
{% endblock %}

{% if res.settle == False %}
    {% block rmenu %}
        <div class="row section center">
            <div data-step="2" data-intro="Your Total Balance With Friend" class="col s7 push-s1 section" style="margin-top: 50px;">
                <h7 class="secondary_text left"><b>YOUR BALANCE</b></h7>
                <br>
                {% if res.balance < 0 %}
                    <p style="margin-bottom: 0px;" class="owe-color left col 9"> You owe {{ res.friend.username }}</p>
                    <h5 style="margin-top: 0px" class="owe-color left col 9"><b>{{ res.balance }}</b></h5>
                {% else %}
                    <p style="margin-bottom: 0px;" class="secondary-icons-text left col 12" style="margin-bottom: 0px;"> {{ res.friend.username }} owes you</p>
                    <h5 style="margin-top: 0px" class="secondary-icons-text left col 9"><b>{{ res.balance }}</b></h5>
                {% endif %}
            </div>
        </div>
    {% endblock %}
{% endif %}

{% block content %}

    <div id="modal-settle-up" class="modal settleup-modal">
        <div class="container modal-content">
            <h4 style="text-align: center">Settle up</h4>
            <form method="post" action="{% url 'UserProfile:settle_up' %}">
                {% csrf_token %}
                <div class="row section center">
                    <span class="section center" style="margin-top: 20px">
                        Are you sure you want to settle up all dongs with {{ res.friend.username }}?
                    </span>
                </div>
                <div class="row section">
                    <div class="col s6">
                        <button class="modal-footer btn waves-effect waves-light red modal-close"
                                type="button" style="text-align: center">
                            No
                            <i class="large material-icons right">close</i>
                        </button>
                    </div>
                    <div class="col s6">
                        <button class="modal-footer btn waves-effect waves-light green" style="text-align: center"
                                type="submit">
                            Yes
                            <i class="large material-icons right">send</i>
                        </button>
                    </div>
                </div>
                <input type="hidden" value="{{ res.friend.email }}" name="friend_email">
            </form>
        </div>
    </div>
    <div class="collapsible" style="margin: -2%; box-shadow: unset">
        <div class="col s12 light_primary_color"
             style="height: 90px; margin-top:5px; border-bottom: 1px solid lightgrey;">
            <img class="left circle section" height="90" width="60" src="{{ res.friend.get_picture }}"/>
            <h4 class="left-align col s2">{{ res.friend.username }}</h4>
            <a class="modal-trigger" href="#cdong-modal">
            </a>

            <a  class="modal-trigger" href="#modal-settle-up"><button data-step="1" data-intro="Settle Up With Friend Here" style="margin-top: 25px;"
                    class="col s2 btn-flat text_icons push-s7 btn {% if res.balance == 0 %} disabled {% endif %} waves-effect waves-light accent_color">Settle up
            </button>
                </a>
        </div>
    </div>

    {% if res.settle == True %}
        <div class="row section center">
            <i style="margin-top: 50px;" class="circle material-icons large secondary-icons-text center">done_all</i>
            <h6 class="secondary_text">You and {{ res.friend.username }} are all settled up.</h6>

        </div>
    {% else %}

        {% if res.dongs %}
            <ul data-step="3" data-intro="Your Dongs With Friend" class="collapsible" style="margin: -2%; box-shadow: unset">
                {% for dong in res.dongs %}
                    <li>
                        <div class="collapsible-header">
                            <a style="font-size: 90%"><b>{{ dong.dong.get_date.month }} {{ dong.dong.get_date.day }}</b></a>
                            <a style="font-size: 60%; margin-right: 1%"><b>{{ dong.dong.get_date.year }}</b></a>
                            <i class="material-icons">local_atm</i>
                            {{ dong.dong.name }}
                            {% if dong.counting > 0 %}
                                <span style="width: 20%" class="new badge" data-badge-caption="you lent"
                                      dir="rtl">{{ dong.counting }}</span>
                            {% elif dong.counting == 0 %}
                                <span style="width: 20%" class="badge" data-badge-caption="not involved" dir="rtl"></span>
                            {% else %}
                                <span style="width: 20%" class="new badge red" data-badge-caption="you owe"
                                      dir="rtl">{{ dong.counting }}</span>
                            {% endif %}
                        </div>
                        <div class="collapsible-body">
                            {% dong_info dong.dong %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endif %}

{% endblock %}